#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# z
. `brew --prefix`/etc/profile.d/z.sh
function precmd () {
    z --add "$(pwd -P)"
}

# nvm
source $(brew --prefix nvm)/nvm.sh
if type nvm  > /dev/null 2>&1; then
    nvm use 0.10
fi

# rbenv
export PATH=$HOME/.rbenv/shims:$PATH
