#
# Executes commands at the start of an interactive session.
#
# Authors:
#   yukiyo <yuki@giamnote.net>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# z
. `brew --prefix`/etc/profile.d/z.sh
function precmd () {
    z --add "$(pwd -P)"
}

# nvm
source $(brew --prefix nvm)/nvm.sh
export NVM_DIR=~/.nvm
if type nvm  > /dev/null 2>&1; then
    nvm use 0.10
fi

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# peco
for f (~/dotfiles/zsh/peco-sources/*) source "${f}" # load peco sources
bindkey '^r' peco-select-history
